javascript_compressor: closure
package_path: "javascripts/"
gzip_assets: off

javascripts:
  application.min:
    - public/javascripts/vendor/jquery-1.8.2.js
    - public/javascripts/application.js

# stylesheets:
#   common:
#     - public/stylesheets/reset.css
#     - public/stylesheets/widgets/*.css
#   workspace:
#     - public/stylesheets/pages/workspace.css
#   empty:
#     - public/stylesheets/pages/empty.css